# syntax=docker/dockerfile:1
FROM ubuntu:noble-20260210.1
LABEL org.opencontainers.image.authors="Maximilian Wende <maximilian.wende@freiberginstruments.com>"
LABEL Description="Image for building and debugging arm-embedded projects from git"
ADD Dockerfile.noble-1 /

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update
RUN apt-get install -y build-essential cmake gcc-arm-none-eabi ninja-build
